import Colors from "../logic/colors.js";

export const UNIQUE_COLOR_LIST = [
  { code: "blauw", kit: "Enkelvoudig", colors: [Colors.BLUE] },
  { code: "rood", kit: "Enkelvoudig", colors: [Colors.RED] },
  { code: "wit", kit: "Enkelvoudig", colors: [Colors.WHITE] },
  { code: "groen", kit: "Enkelvoudig", colors: [Colors.GREEN] },
  { code: "wit blauw", kit: "Meerdere", colors: [Colors.WHITE, Colors.BLUE] },
  { code: "rood wit", kit: "Meerdere", colors: [Colors.RED, Colors.WHITE] },
  { code: "wit-groen", kit: "Meerdere", colors: [Colors.WHITE, Colors.GREEN] },
  { code: "zwart", kit: "Enkelvoudig", colors: [Colors.BLACK] },
  { code: "oranje", kit: "Enkelvoudig", colors: [Colors.ORANGE] },
  {
    code: "donkerblauw-rood",
    kit: "Meerdere",
    colors: [Colors.DARK_BLUE, Colors.RED],
  },
  { code: "paars", kit: "Enkelvoudig", colors: [Colors.PURPLE] },
  { code: "geel", kit: "Enkelvoudig", colors: [Colors.YELLOW] },
  { code: "donkergrijs", kit: "Enkelvoudig", colors: [Colors.DARK_GREY] },
  { code: "donker grijs", kit: "Enkelvoudig", colors: [Colors.DARK_GREY] },
  {
    code: "oranje met zwarte veegprint",
    kit: "Meerdere",
    colors: [Colors.ORANGE, Colors.BLACK],
  },
  {
    code: "wit-rood gestreept",
    kit: "Gestreept",
    colors: [Colors.WHITE, Colors.RED],
  },
  {
    code: "zalm of wit",
    kit: "Meerdere",
    colors: [Colors.SALMON, Colors.WHITE],
  },
  {
    code: "paars/zwart",
    kit: "Meerdere",
    colors: [Colors.PURPLE, Colors.BLACK],
  },
  { code: "rood/zwart", kit: "Meerdere", colors: [Colors.RED, Colors.BLACK] },
  {
    code: "blauw en geel",
    kit: "Meerdere",
    colors: [Colors.BLUE, Colors.YELLOW],
  },
  { code: "rood-wit", kit: "Meerdere", colors: [Colors.RED, Colors.WHITE] },
  {
    code: "zwart / wit",
    kit: "Meerdere",
    colors: [Colors.BLACK, Colors.WHITE],
  },
  { code: "groen-wit", kit: "Meerdere", colors: [Colors.GREEN, Colors.WHITE] },
  { code: "groen/wit", kit: "Meerdere", colors: [Colors.GREEN, Colors.WHITE] },
  { code: "bordeaux", kit: "Enkelvoudig", colors: [Colors.BORDEAUX] },
  { code: "licht blauw", kit: "Enkelvoudig", colors: [Colors.LIGHT_BLUE] },
  { code: "blauwe", kit: "Enkelvoudig", colors: [Colors.BLUE] },
  {
    code: "blauw met gele strepen",
    kit: "Gestreept",
    colors: [Colors.BLUE, Colors.YELLOW],
  },
  {
    code: "blauw-turquoise",
    kit: "Meerdere",
    colors: [Colors.BLUE, Colors.TURQUOISE],
  },
  { code: "rode/witte", kit: "Meerdere", colors: [Colors.RED, Colors.WHITE] },
  {
    code: "wit met groene strepen",
    kit: "Gestreept",
    colors: [Colors.WHITE, Colors.GREEN],
  },
  { code: "zalm-kleur", kit: "Enkelvoudig", colors: [Colors.SALMON] },
  {
    code: "geel/zwart",
    kit: "Meerdere",
    colors: [Colors.YELLOW, Colors.BLACK],
  },
  { code: "blauw/wit", kit: "Meerdere", colors: [Colors.BLUE, Colors.WHITE] },
  { code: "blauw/geel", kit: "Meerdere", colors: [Colors.BLUE, Colors.YELLOW] },
  {
    code: "oranje/zwart",
    kit: "Meerdere",
    colors: [Colors.ORANGE, Colors.BLACK],
  },
  {
    code: "zwart/oranje",
    kit: "Meerdere",
    colors: [Colors.BLACK, Colors.ORANGE],
  },
  {
    code: "zwart/geel gestreept",
    kit: "Gestreept",
    colors: [Colors.BLACK, Colors.YELLOW],
  },
  {
    code: "lichtblauw/donkerblauw",
    kit: "Meerdere",
    colors: [Colors.LIGHT_BLUE, Colors.DARK_BLUE],
  },
  { code: "grijs", kit: "Enkelvoudig", colors: [Colors.GREY] },
  { code: "donkergroen", kit: "Enkelvoudig", colors: [Colors.DARK_GREEN] },
  {
    code: "bordeaux/donker blauw",
    kit: "Meerdere",
    colors: [Colors.BORDEAUX, Colors.DARK_BLUE],
  },
  { code: "donker blauw", kit: "Meerdere", colors: [Colors.DARK_BLUE] },
];
